; [env:esp32dev]
; platform = espressif32
; board = esp32dev
; framework = arduino
; monitor_speed = 115200

; # PlatformIO automatically manages these dependencies!
; lib_deps =
;     bblanchon/ArduinoJson @ ^7.0.0

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

# Force the compiler to disable PSRAM tracking to prevent boot panics
build_flags = 
    -DBOARD_HAS_PSRAM=0
    -DARDUINO_USB_CDC_ON_BOOT=1

# Specify LittleFS partitioning layout
board_build.filesystem = littlefs

# Standard partition table for an 8MB Flash device (No PSRAM)
board_build.partitions = default_8MB.csv

lib_deps =
    esphome/ESPAsyncWebServer-esphome @ ^3.2.2
    knolleary/PubSubClient @ ^2.8

# Tell PlatformIO to compile everything in src, EXCEPT the testing folder
build_src_filter = +<*> -<testing/>

