#include <WiFi.h>
#include <ESPAsyncWebServer.h>
#include <LittleFS.h>
#include <PubSubClient.h>

// =========================================================================
// 📡 NETWORK & HARDWARE CONFIGURATION PARAMETERS
// =========================================================================
// 1. Standalone Local Hotspot Credentials (Generated by ESP32)
const char* ap_ssid = "ESP32S3-Security-Hub";
const char* ap_pass = "secure1234";

// 2. Home Infrastructure Router Credentials (Targeting 2.4 GHz Band)
const char* home_ssid = "WireShark-2.4Ghz"; // <-- Change to your router name
const char* home_pass = "$p!D3y-PasS";    // <-- Change to your router password

// 3. Cloud MQTT Broker Broker Parameters
const char* mqtt_server = "broker.hivemq.com";
const int mqtt_port = 1883; // Standard unencrypted TCP port
const char* mqtt_topic = "sgsits/mechanical/laserSecurity/alerts";

// =========================================================================
// 🎛️ OBJECT INSTANTIATIONS & GLOBAL SYSTEM VARIABLES
// =========================================================================
AsyncWebServer server(80);
WiFiClient espClient;
PubSubClient mqttClient(espClient);

// Shared Global Memory Layout Matrix
int globalLdrRaw = 450;
bool globalIsMuted = false;
String globalLastAction = "RESET";

unsigned long lastMqttRetry = 0;
unsigned long lastHeartbeat = 0;

// =========================================================================
// 🔄 UNIFIED STATE BROADCAST COMPILER
// =========================================================================
void broadcastSystemStateMQTT() {
    if (mqttClient.connected()) {
        // Compile variables into the structured JSON expected by data/script.js
        String payload = "{\"ldr_raw\":" + String(globalLdrRaw) + 
                         ",\"is_muted\":" + (globalIsMuted ? String("true") : String("false")) + 
                         ",\"last_action\":\"" + globalLastAction + "\"}";
                         
        mqttClient.publish(mqtt_topic, payload.c_str());
        Serial.println("[MQTT WAN] Dispatched synchronization packet: " + payload);
    } else {
        Serial.println("[MQTT WARN] Packet dropped. Cloud pipeline is disconnected.");
    }
}

// Global Callback handler intercepting actions coming downward from the cloud tabs
void mqttCallback(char* topic, byte* payload, unsigned int length) {
    String message = "";
    for (unsigned int i = 0; i < length; i++) {
        message += (char)payload[i];
    }
    Serial.println("[MQTT INCOMING] Cloud packet intercepted: " + message);

    // If an incoming instruction arrived from an internet tab, digest it into variables
    // Simple direct parse matching our simulation script buttons
    if (message.indexOf("\"last_action\":\"BREACH\"") > 0) {
        globalLdrRaw = 3850;
        globalIsMuted = false;
        globalLastAction = "BREACH";
    } 
    else if (message.indexOf("\"last_action\":\"RESET\"") > 0) {
        globalLdrRaw = 450;
        globalIsMuted = false;
        globalLastAction = "RESET";
    } 
    else if (message.indexOf("\"last_action\":\"MUTE\"") > 0) {
        globalIsMuted = true;
        globalLastAction = "MUTE";
    }
}

// Non-blocking stateful MQTT connection supervisor
void handleMqttReconnection() {
    if (!mqttClient.connected()) {
        unsigned long now = millis();
        if (now - lastMqttRetry > 5000) { // Non-blocking attempt every 5 seconds
            lastMqttRetry = now;
            Serial.print("[MQTT LOG] Connecting to HiveMQ broker matrix...");
            
            String clientId = "ESP32S3_Gateway_" + String(random(0, 9999));
            if (mqttClient.connect(clientId.c_str())) {
                Serial.println(" CONNECTED!");
                mqttClient.subscribe(mqtt_topic);
                // Sync current hardware data state immediately upon reconnecting
                broadcastSystemStateMQTT();
            } else {
                Serial.print(" FAILED, rc=");
                Serial.println(mqttClient.state());
            }
        }
    }
}

// =========================================================================
// 🚀 CORE SETUP INITIALIZATION INTERFACE
// =========================================================================
void setup() {
    Serial.begin(115200);
    delay(2500); // Critical Arch Linux native USB CDC handshake buffer
    
    Serial.println("\n==============================================");
    Serial.println("[SYSTEM CORE] INITIALIZING NETWORK TRANSCEIVER LAYER...");
    Serial.println("==============================================");

    if (!LittleFS.begin()) {
        Serial.println("[ERROR] LittleFS Mounting Failure! Process halted.");
        return;
    }

    // 1. Bind Dual-Mode WiFi Architecture (AP + STA)
    WiFi.mode(WIFI_AP_STA);

    // 2. Spawn Standalone Local Safe Hotspot
    WiFi.softAP(ap_ssid, ap_pass);
    Serial.print("[AP] Isolated Network Interface Spawned. Gateway IP: ");
    Serial.println(WiFi.softAPIP());

    // 3. Authenticate Background Link with Home Router Gateway
    Serial.print("[STA] Launching infrastructure handshake with: ");
    Serial.println(home_ssid);
    WiFi.begin(home_ssid, home_pass);

    // Only wait 5 seconds max during boot so chip doesn't stall if router is down
    int wifiTimeout = 0;
    while (WiFi.status() != WL_CONNECTED && wifiTimeout < 10) {
        delay(500);
        Serial.print(".");
        wifiTimeout++;
    }

    if (WiFi.status() == WL_CONNECTED) {
        Serial.println("\n[STA] Connection Stabilized!");
        Serial.print("[STA] Router Assigned IP Address: ");
        Serial.println(WiFi.localIP());
    } else {
        Serial.println("\n[STA WARN] External router handshake timed out. Operating in fallback LAN mode.");
    }

    // 4. Bind Cloud MQTT Networking Array Configs
    mqttClient.setServer(mqtt_server, mqtt_port);
    mqttClient.setCallback(mqttCallback);

    // =========================================================================
    // 🛠️ ASYNC HTTP SERVER ENDPOINTS & API ROUTING
    // =========================================================================
    // Serve Static Dashboard Frontend Assets directly from LittleFS flash memory
    server.on("/", HTTP_GET, [](AsyncWebServerRequest *request){
        request->send(LittleFS, "/index.html", "text/html");
    });
    server.on("/style.css", HTTP_GET, [](AsyncWebServerRequest *request){
        request->send(LittleFS, "/style.css", "text/css");
    });
    server.on("/script.js", HTTP_GET, [](AsyncWebServerRequest *request){
        request->send(LittleFS, "/script.js", "application/javascript");
    });

    // ROUTE 1: Local Telemetry Polling Channel (Hits 5 times a second by local AP tabs)
    server.on("/api/status", HTTP_GET, [](AsyncWebServerRequest *request) {
        String jsonResponse = "{\"ldr_raw\":" + String(globalLdrRaw) + 
                              ",\"is_muted\":" + (globalIsMuted ? String("true") : String("false")) + 
                              ",\"last_action\":\"" + globalLastAction + "\"}";
        request->send(200, "application/json", jsonResponse);
    });

    // ROUTE 2: Local Command Gateway Interceptor (Fired by actions clicked on offline tabs)
    server.on("/api/action", HTTP_GET, [](AsyncWebServerRequest *request) {
        if (request->hasParam("cmd")) {
            String command = request->getParam("cmd")->value();
            
            if (command == "sim_breach") {
                globalLdrRaw = 3850;
                globalIsMuted = false;
                globalLastAction = "BREACH";
            } 
            else if (command == "reset") {
                globalLdrRaw = 450;
                globalIsMuted = false;
                globalLastAction = "RESET";
            } 
            else if (command == "mute") {
                globalIsMuted = true;
                globalLastAction = "MUTE";
            }
            
            // 🔥 The Sync Bridge: Propagate local action up to the internet cloud instantly
            broadcastSystemStateMQTT(); 
            request->send(200, "text/plain", "ACK");
        } else {
            request->send(400, "text/plain", "BAD REQUEST");
        }
    });

    server.begin();
    Serial.println("[SYSTEM CORE] All Web Services Bound to Port 80. Engine Online.");
}

// =========================================================================
// 🔄 REAL-TIME MAIN PROCESS MAINTENANCE LOOP
// =========================================================================
void loop() {
    // If we have internet access, keep the MQTT subscription connection alive
    if (WiFi.status() == WL_CONNECTED) {
        handleMqttReconnection();
        mqttClient.loop();
    }

    // --- 📡 Optional: Low Frequency Background Telemetry Sync ---
    // Every 4 seconds, verify that the router browser tabs stay completely current
    unsigned long currentMillis = millis();
    if (currentMillis - lastHeartbeat > 4000) {
        lastHeartbeat = currentMillis;
        if (WiFi.status() == WL_CONNECTED && mqttClient.connected()) {
            broadcastSystemStateMQTT();
        }
    }

    // Hardware sensor reading logic hooks here later (analogRead(4))...
}